#!/bin/bash

#说明
#执行可以加参数
#下面A代表参数
#--BUILD_TYPE=A  #A代表要编译交叉编译器
#--clean 清除config.make

EXPR="expr --"
NOTFOUND=""
PLATTYPE=""
CLEAN=""
DEBUG_TYPE=""

CONFIG_LIST=""

SRCROOT=`pwd`
TOP_DIR=`pwd`
#`cd ../;pwd`

if [  -d "${TOP_DIR}/Lib" ] ; then
	for file in `ls ${TOP_DIR}/Lib`
	do
	CONFIG_LIST+=" "$file
	done  
fi

if [ "$CONFIG_LIST" == "$NOTFOUND" ] ; then
	CONFIG_LIST=arm-xxxx-;
fi

# parse arguments
while [ "$1" != "" ] ; do
	val=`$EXPR "$1" : '--\(.*\)'`
	if [ "$val" = "clean" ] ; then
		CLEAN=$val
	fi
	if [ "$val" = "debug" ] ; then
		DEBUG_TYPE="1"
	fi
	val=`$EXPR "$1" : '--plat=\(.*\)'`
	if [ "$val" != "$NOTFOUND" ] ; then
		PLATTYPE=$val;
	fi
	shift
done

#SRCROOT=`cd ../../;pwd`
# create config.make
if [ "${PLATTYPE}" != "$NOTFOUND" ]; then
	echo '# config.make generated by configure script' >./config.make
	echo "TOP_DIR=${TOP_DIR}">>./config.make
	echo "PLATTYPE=${PLATTYPE}">>./config.make
elif [ "${CLEAN}" = "clean" ]; then 
	if [ -f config.make ]; then
	rm config.make
	fi
	echo clean config.make success!
else
	echo useage: ./configure
	echo          --plat=["${CONFIG_LIST}"]
	echo          --debug
	echo          --clean
	exit 0;
fi

if [ "${DEBUG_TYPE}" != "$NOTFOUND" ]; then
	echo "debug=1">>./config.make
fi

